### ISSUE TITLE
Kernelspecs doesn't find python kernel from sys-dir

### ISSUE THREAD

**Issue by lgeiger** [nteract/kernelspecs#18]
`kernelspecs` differs from `jupyter kernelspec list --json` on my system.

The output of `jupyter kernelspec list --json` is:

```
"kernelspecs": {
  "root": {
    "resource_dir": "/Users/lukasgeiger/Library/Jupyter/kernels/root",
    "spec": {
      "language": "c++",
      "display_name": "ROOT Prompt",
      "env": {},
      "argv": [
        "python",
        "-m",
        "IPython.kernel",
        "-f",
        "{connection_file}",
        "-c",
        "import ROOT;ROOT.toCpp();"
      ]
    }
  },
  "python2": {
    "resource_dir": "/usr/local/lib/python2.7/site-packages/ipykernel/resources",
    "spec": {
      "language": "python",
      "display_name": "Python 2",
      "env": {},
      "argv": [
        "/usr/local/opt/python/bin/python2.7",
        "-m",
        "ipykernel",
        "-f",
        "{connection_file}"
      ]
    }
  }
}
```

Though `kernelspecs` doesn't recognize the python kernel on my system:

```
{ root:
   { name: 'root',
     files:
      [ '/Users/lukasgeiger/Library/Jupyter/kernels/root/.DS_Store',
        '/Users/lukasgeiger/Library/Jupyter/kernels/root/kernel.json' ],
     resources_dir: '/Users/lukasgeiger/Library/Jupyter/kernels/root',
     spec: { language: 'c++', argv: [Object], display_name: 'ROOT Prompt' } } }
```

**Comment by lgeiger** [comment]
Today I tried it again and everything works as expected. I have no idea what I changed :)

**Comment by lgeiger** [comment]
I had to use the `ipython kernel install` command. Now the output matches.

**Comment by rgbkrk** [comment]
From a UX standpoint, what could we do to either help discover more or require on install for jupyter?

**Comment by lgeiger** [comment]
Jupyter gets the kernelspec directly from ipython if no python kernel is found (https://github.com/jupyter/jupyter_client/blob/master/jupyter_client/kernelspec.py#L135), but I don't know if this can be done in the node module as well.

**Comment by rgbkrk** [comment]
After a release of `jupyter-paths` and adaptation code to use `opts.askJupyter`, `kernelspecs` could pick it up:

https://github.com/nteract/jupyter-paths/blob/master/index.js#L176

**Comment by rgbkrk** [comment]
I'd rather that choice be on the node-based frontend using these libraries though, as I don't want to expect everyone to have jupyter installed to use nteract.
